apiVersion: apps/v1
kind: Deployment
metadata:
  name: abctechnologies-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: abctechnologies-app
  template:
    metadata:
      labels:
        app: abctechnologies-app
    spec:
      containers:
      - name: abctechnologies-app
        image: 10061982834282/abctechnologies-app:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
