apiVersion: v1
kind: Service
metadata:
  name: abctechnologies-app
spec:
  selector:
    app: abctechnologies-app
  ports:
  - port: 8003
    targetPort: 8080
    nodePort: 31884
  type: LoadBalancer
